export const GLOBAL_PREFIX = '/api';
export const SALT_ROUNDS = 10;
export const RECOVERY_CODE_EXPIRATION_TIME_IN_HOURS = 1;
export const EMAIL_SERVICE = 'gmail';

export const ENV_VARIABLE_NAMES = {
  AUTH_CONFIRMATION_CODE_EXPIRATION_TIME_IN_HOURS:
    'AUTH_CONFIRMATION_CODE_EXPIRATION_TIME_IN_HOURS',
  DB_NAME: 'DB_NAME',
  MONGO_URL: 'MONGO_URL',
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  SERVER_URL: 'SERVER_URL',
} as const;
