export const GLOBAL_PREFIX = '/api';
// TODO: refactor
export const RECOVERY_CODE_EXPIRATION_TIME_IN_HOURS = 1;

export const ENV_VARIABLE_NAMES = {
  ACCESS_TOKEN_EXPIRATION_TIME: 'ACCESS_TOKEN_EXPIRATION_TIME',
  CONFIRMATION_CODE_EXPIRATION_TIME_IN_HOURS:
    'CONFIRMATION_CODE_EXPIRATION_TIME_IN_HOURS',
  DB_NAME: 'DB_NAME',
  JWT_SECRET: 'JWT_SECRET',
  MONGO_URL: 'MONGO_URL',
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  SERVER_URL: 'SERVER_URL',
} as const;

export enum ENVIRONMENTS {
  DEVELOPMENT = 'development',
  STAGING = 'staging',
  PRODUCTION = 'production',
  TESTING = 'testing',
}
